// <auto-generated />
using ComputerPartsShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ComputerPartsShop.Data.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    [Migration("20210912110950_EditedRamEntityAndAddedGeneration")]
    partial class EditedRamEntityAndAddedGeneration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ComputerPartsShop.Data.Models.RamGeneration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RamGenerations");
                });

            modelBuilder.Entity("ComputerPartsShop.Data.Models.RandomAccessMemory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("CasLatency")
                        .HasColumnType("int");

                    b.Property<int>("Frequency")
                        .HasColumnType("int");

                    b.Property<int>("GenerationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GenerationId");

                    b.ToTable("RandomAccessMemories");
                });

            modelBuilder.Entity("ComputerPartsShop.Data.Models.RandomAccessMemory", b =>
                {
                    b.HasOne("ComputerPartsShop.Data.Models.RamGeneration", "Generation")
                        .WithMany("RandomAccessMemories")
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Generation");
                });

            modelBuilder.Entity("ComputerPartsShop.Data.Models.RamGeneration", b =>
                {
                    b.Navigation("RandomAccessMemories");
                });
#pragma warning restore 612, 618
        }
    }
}
